suppressPackageStartupMessages(library(argparser, verbose=FALSE))
parser <- arg_parser("Generate and format PoPS feature matrix")
parser <- add_argument(parser, "--name", help="name of run", type="character")
parser <- add_argument(parser, "--inputData", help="input data", type="character")
parser <- add_argument(parser, "--cores", help="number of cores", type="numeric", default = max(c(1, round(parallel::detectCores()/2))))
parser <- add_argument(parser, "--numberPcs", help="number of PCs to include", type="character", default="elbow")
parser <- add_argument(parser, "--varGenes", help="var genes", type="numeric", default=3000)
parser <- add_argument(parser, "--clusRes", help="clus res", type="numeric", default=0.8)
parser <- add_argument(parser, "--inputAnnot", help="input annotation", type="character", default="none")
parser <- add_argument(parser, "--rowAnnot", help="input row annotation file (used with colAnnot for MatrixMarket format files)", type="character", default="none")
parser <- add_argument(parser, "--colAnnot", help="input column annotation file (used with rowAnnot for MatrixMarket format files)", type="character", default="none")
parser <- add_argument(parser, "--isProcessed", help="is already processed flag", flag = TRUE)
parser <- add_argument(parser, "--rowIdType", help="type of row ID", type="character", default="human_symbol")
parser <- add_argument(parser, "--plotClustree", help="generate clustree plot, can take a while for large datasets", flag=TRUE)
parser <- add_argument(parser, "--minFeatures", help="Minimum ammount of features for Searat object", type="numeric", default=200)
parser <- add_argument(parser, "--DEGenesPlotHeight", help="Height (inch) of the DEGenesOnUmap plot", type="numeric", default=15)
parser <- add_argument(parser, "--dontCompress", help="Flag that disables gzipping output", flag=TRUE)
parser <- add_argument(parser, "--generateBatchId", help="Use generated batch IDs when inputting multiple files", flag=TRUE)
parser <- add_argument(parser, "--display", help="Display plots as they are generated. This may or may not work when using Rscript depending on display devices", flag=TRUE)
parser <- add_argument(parser, "--integrationAnchorDims", help="Number of dimensions to use for integration anchors of multiple input files", type="numeric", default=30)
parser <- add_argument(parser, "--useIntegrationSampleSizeReference", help="Use sample size as reference data when finding integration anchors", flag=TRUE)
parser <- add_argument(parser, "--markerGenes", help="Known marker genes to compare to, comma separated", type="character", default="")
parser <- add_argument(parser, "--outputDir", help="Base folder for output (will make outputDir/features outputDir/data, etc", type="character", default="../")
parser <- add_argument(parser, "--geneAnnot", help="File with gene annotation (and genes to keep), if no file is provided all genes/rows will be kept", type="character", default="")
parser <- add_argument(parser, "--conversionDir", help="directory with files used for converting to ENSG, leave empty to skip conversion", type="character", default="")